config/routes.rb
Edison::Engine.routes.draw do

	resources 	:experiment_admin
	resources 	:experiment_url_pattern_admin
	resources	:variant_admin
	
end

app/models/edison/application_record.rb
module Edison
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/edison/experiment.rb
module Edison

	class Experiment < ApplicationRecord

		enum status: { 'archive' => -1, 'draft' => 0, 'active' => 1 }

		has_many	:experiment_url_patterns

		has_many	:variants
		has_many 	:trials, through: :variants#, source: :trial

		include FriendlyId
		friendly_id :title, use: :slugged

		def concluded?
			if self.has_expired?
				return true
			end

			if self.has_max_trials?
				self.end_at = Time.zone.now
				self.save
				return true
			end
		end

		def has_expired?( args = {} )
			args[:now] ||= Time.zone.now
			self.end_at.present? && args[:now] >= self.end_at
		end

		def has_max_trials?
			self.max_trials.present? && self.trials.count > self.max_trials
		end

		def started?( args = {} )
			args[:now] ||= Time.zone.now
			self.start_at.present? && args[:now] >= self.start_at
		end

	end

end

app/models/edison/experiment_url_pattern.rb
module Edison

	class ExperimentUrlPattern < ActiveRecord::Base
		belongs_to :experiment
	end

end

app/models/edison/trial.rb
module Edison

	class Trial < ApplicationRecord
		
		belongs_to 	:experiment

		belongs_to 	:client, class_name: 'Bunyan::Client', optional: true
		belongs_to	:variant, optional: true



		def generate_variant

			return self.variant if self.variant.present?

			case self.experiment.sample_type
			when 'weighted'
				# TODO
				stupid_array = []
				self.experiment.variants.each do |v|
					weight = v.weight < 1 ? v.weight * 10 : v.weight
					weight.times do
						stupid_array << v
					end
				end

				self.variant = stupid_array.sample

			when '5050'
				self.variant = self.experiment.variants.active.order( cached_participant_count: :asc ).first
			else # random
				self.variant = self.experiment.variants.active.order( Arel.sql("random()") ).first
			end

			self.save
			self.variant.increment!( :cached_participant_count )

		end
		
	end

end

app/models/edison/variant.rb
module Edison

	class Variant < ApplicationRecord

		enum status: { 'archive' => -1, 'draft' => 0, 'active' => 1 }

		belongs_to		:experiment

		has_many		:trials

		validate :is_control_toggle


		def self.control
			where( is_control: true ).first
		end


		def confidence_interval( opts={} )
			return 0 if self.trials.empty?

			opts[:confidence] = opts[:confidence].to_s

			opts[:confidence] ||= '90' # 90% confidence
			confidence_factors = { '67' => 1, '75' => 1.15, '80' => 1.28, '90' => 1.645, '95' => 1.96, '99' => 2.575, '999' => 5 }
			confidence = confidence_factors[ opts[:confidence] ] || 1.96
			return Math.sqrt( self.conversion_rate( opts ) * ( 1 - self.conversion_rate( opts ) ) / self.trials.count ) * confidence
		end


		def conversion_rate( opts={} )
			return 0 if self.trials.empty?
			total_conversions = self.conversions( opts )
			return ( total_conversions.to_f / self.trials.count.to_f )
		end


		def conversions( opts={} )
			return 0 if self.trials.empty?
			event = opts[:event] || opts[:for] || self.experiment.conversion_event

			path = opts[:path] || opts[:page] || opts[:page_path] || self.experiment.conversion_path

			uniq = !!opts.fetch( :uniq, true )

			conversions = Bunyan::Event.where( name: event ).where( client_id: self.participants )

			# only include conversions from when the experiemnt actually started
			conversions = conversions.where( "created_at >= :t", t: self.trials.minimum( :created_at ) )

			if self.experiment.has_expired?
				# only include conversions from before the experiemnt ended
				conversions = conversions.where( "created_at <= :t", t: self.experiment.end_at )
			end

			conversions = conversions.where( page_path: path ) if event == 'pageview' && path.present?

			conversions = conversions.distinct if uniq

			conversions = conversions.count

		end



		def participants
			Bunyan::Client.where( id: self.trials.pluck( :client_id ) )
		end

		protected

		def is_control_toggle
			if not( self.is_control? ) && self.is_control_changed? && self.experiment.variants.active.where( is_control: true ).where.not( id: self.id ).count == 0
				self.errors.add( :is_control, "can't be delesected.  To deselect a variant as control you must toggle it to a different variant." )
			end

			if self.is_control? && self.status_changed? && not( self.active? )
				self.errors.add( :status, "can't be non-active when set as control.  To change the status select another variant as control first." )
			elsif self.is_control? && not( self.active? )
				self.errors.add( :is_control, "can't be selected for a non-active variant." )
			end

		end

	end

end

app/controllers/edison/application_controller.rb
module Edison
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/edison/concerns/application_controller_concern.rb
module Edison
	module Concerns

		module ApplicationControllerConcern
			extend ActiveSupport::Concern

			included do
				helper Edison::ApplicationHelper
			end


			####################################################
			# Class Methods

			module ClassMethods

			end


			####################################################
			# Instance Methods


			protected

		end

	end
end

app/controllers/edison/experiment_admin_controller.rb
module Edison
	class ExperimentAdminController < ApplicationAdminController


		def create
			@experiment = Experiment.new( experiment_params )

			@experiment.start_at ||= Time.zone.now
			@experiment.end_at ||= @experiment.start_at + 1.month

			@experiment.save
			redirect_to edit_experiment_admin_path( @experiment )
		end

		def index
			@experiments = Experiment.all.order( created_at: :desc ).page( params[:page] )
		end

		def edit
			@experiment = Experiment.friendly.find( params[:id] )
			@control = @experiment.variants.control

		end

		def update
			@experiment = Experiment.friendly.find( params[:id] )
			@experiment.update( experiment_params )
			set_flash 'Experiment Updated'
			redirect_to edit_experiment_admin_path( @experiment )

		end


		private
			def experiment_params
				params.require( :experiment ).permit( :title, :description, :sample_type, :conclusion_type, :conversion_event, :conversion_path, :start_at, :end_at, :max_trials, :status, :conversion_window_days )
			end
	end
end

app/controllers/edison/experiment_url_pattern_admin_controller.rb
module Edison
	class ExperimentUrlPatternAdminController < ApplicationAdminController


		def create
			@experiment_url_pattern = ExperimentUrlPattern.new( experiment_url_pattern_params )
			@experiment_url_pattern.save
			set_flash 'Experiment URL Pattern Created'
			redirect_to edit_experiment_admin_path( @experiment_url_pattern.experiment_id )
		end

		def destroy
			@experiment_url_pattern = ExperimentUrlPattern.find( params[:id] )
			@experiment_url_pattern.destroy
			set_flash 'Experiment URL Pattern Deleted'
			redirect_to edit_experiment_admin_path( @experiment_url_pattern.experiment_id )
		end

		def index
			@experiment_url_patterns = ExperimentUrlPattern.all.order( created_at: :desc ).page( params[:page] )
		end

		def edit
			@experiment_url_pattern = ExperimentUrlPattern.find( params[:id] )
		end

		def update
			@experiment_url_pattern = ExperimentUrlPattern.find( params[:id] )
			@experiment_url_pattern.update( experiment_url_pattern_params )
			set_flash 'Experiment URL Pattern Updated'
			redirect_to edit_experiment_admin_path( @experiment_url_pattern.experiment_id )

		end


		private
			def experiment_url_pattern_params
				params.require( :experiment_url_pattern ).permit( :experiment_id, :url_pattern )
			end
	end
end

app/controllers/edison/variant_admin_controller.rb
module Edison
	class VariantAdminController < ApplicationAdminController

		def create
			@variant = Variant.new( variant_params )

			if Variant.where( experiment_id: @variant.experiment_id ).count == 0
				@variant.is_control = true
			end

			@variant.save
			redirect_to edit_variant_admin_path( @variant )
		end

		def destroy
			@variant = Variant.find( params[:id] )
			@variant.archive!
			redirect_back( fallback_location: '/admin' )
		end

		def edit
			@variant = Variant.find( params[:id] )
		end

		def update
			@variant = Variant.find( params[:id] )
			@variant.update( variant_params )

			if @variant.errors.present?
				set_flash @variant.errors.full_messages, :danger
			else
				@variant.experiment.variants.where.not( id: @variant.id ).update_all( is_control: false ) if @variant.is_control?
			end

			redirect_back( fallback_location: '/admin' )
		end

		private

			def variant_params
				params.require( :variant ).permit( :experiment_id, :title, :description, :content, :status, :is_control, :gross_margin, :cost_of_acquiring_customers, :costs )
			end
	end
end

app/helpers/edison/application_helper.rb
module Edison
	module ApplicationHelper

		def edison_run_experiment( exp_id, options = {} )
			options[:default] = '' unless options.has_key? :default

			variant = nil

			is_forced = false

			begin
				experiment = Experiment.friendly.find( exp_id )
			rescue ActiveRecord::RecordNotFound
				return options[:default]
			end

			# option to force a variant
			# will return the variant whether or not experiment is active
			# client will not be put into the trial pool
			force_var = options.delete( :force_var )
			if force_var.present?
				variant = experiment.variants.where( is_control: true ).last if force_var == 'control'
				variant ||= experiment.variants.find_by( id: force_var )

				is_forced = variant.present?
			end
			# if force_var is invalid, method should coninute as normally.....

			client_id = Bunyan::Client.find_by( uuid: cookies[:clientuuid] ).try( :id )

			if client_id.nil?
				return options[:default]
			end

			# check if a trial exists for this client
			trial = experiment.trials.where( client_id: client_id ).last

			if trial.nil? && ( experiment.started? && experiment.concluded? )

				# the music's over
				if experiment.conclusion_type == 'control'
					return experiment.variants.where( is_control: true ).last.content
				elsif experiment.conclusion_type == 'winner'
					return experiment.variants.active.order( cached_conversion_count: :desc ).first.content
				else
					return options[:default]
				end

			elsif trial.nil? && ( not( experiment.active? ) || not( experiment.started? ) )
				# the music hasn't started yet
				return options[:default]
			end

			# create one if not - this will assign the client to a variant
			if trial.blank?
				trial = Trial.new(
					experiment_id: experiment.id,
					client_id: client_id
				)
				trial.created_url = request.url if trial.respond_to?(:created_url)
				trial.is_forced = is_forced if trial.respond_to?(:is_forced)
				trial.save
			end

			# if a force var has been requested for this trial, mark it as so
			if trial.respond_to?(:is_forced) && is_forced && !trial.is_forced
				trial.is_forced = is_forced
				trial.save
			end


			if variant.present?
				trial.variant.decrement!( :cached_participant_count ) if trial.variant.present?
				variant.increment!( :cached_participant_count )
				trial.update( variant: variant )
			else
				# method should return the correct variant content ro be rendered as html
				variant = trial.generate_variant
			end

			return variant.content

		end

	end
end

app/views/edison/experiment_admin/_new_modal.html.haml
#new_experiment.modal.fade
	.modal-dialog
		.modal-content
			.modal-header
				%button.close{ type: :button, 'data-dismiss' => 'modal', 'aria-hidden' => 'true' }
					&times;
				%h4.modal-title
					New Experiment
			= form_for Edison::Experiment.new, url: edison.experiment_admin_index_path do |f|
				.modal-body
					.form-group
						= f.label :title
						= f.text_field :title, class: 'form-control'
					.form-group
						= f.label :description
						= f.text_area :description, class: 'form-control'

				.modal-footer
					%button.btn.btn-default{ type: :button, 'data-dismiss' => 'modal' }
						Close
					= f.submit 'Upload', class: 'btn btn-primary'

app/views/edison/experiment_admin/edit.html.haml
.container-fluid
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					= link_to 'Admin', main_app.admin_index_path
				%li
					= link_to 'Experiment Admin',experiment_admin_index_path
				%li
					%strong
						Edit
						= @experiment.title
		.col-xs-2


	= form_for @experiment, url: experiment_admin_path( @experiment ) do |f|

		.row
			.col-xs-8
				.form-group
					= f.text_field :title, class: 'form-control input-lg'
					code:
					= @experiment.slug
				.form-group
					= f.label :description
					= f.text_area :description, class: 'form-control wysiwyg', data: { wysiwyg: { height_min: 100, toolbar_sticky: true, toolbar_preset: 'admin_default' } }



				.col-xs-12
					.well.white-well
						%a.pull-right{ href: '#new_variant', data: { toggle: :modal, target: '#new_variant' } }
							%i.fa.fa-plus
							Add
						%h4
							Variants

						%table.table.table-light.table-bordered{ style: 'margin:0;' }
							%thead
								%th
								%th Title
								%th Participants
								%th Conversions
								%th Rate
								%th Variance (90%)
								%th
								%th


							- if @experiment.variants.empty?
								%tr
									%td{ colspan: 7 }
										\- No Variants Found -

							- @experiment.variants.each do |variant|
								%tr
									%td
										- if variant.is_control?
											%i.fa.fa-check
									%td
										%a{ href: edit_variant_admin_path( variant ) }
											= variant.title
									%td
										= variant.cached_participant_count
									%td
										= variant.conversions
									%td
										= number_to_percentage( variant.conversion_rate * 100 )
										%br
										- if variant == @control
											Control
										- else
											= number_to_percentage( (variant.conversion_rate * 100) - ( @control.conversion_rate * 100 ) )
											- if variant.conversion_rate > @control.conversion_rate
												better
											- else
												worse
											than control

									%td
										+/-
										= number_to_percentage( variant.confidence_interval * 100 )


									%td
										- if variant == @control
											Control
										- else
											= (( variant.conversions - @control.conversions ).abs * 0.5 ) ** 2
											- if (( variant.conversions - @control.conversions ).abs * 0.5 ) ** 2 < @experiment.trials.count
												Insignificant
											- elsif (( variant.conversions - @control.conversions ).abs * 0.5 ) ** 2 < 2 * @experiment.trials.count
												Exremely Significant
											- else
												Significant



									%td.text-center

										%a.btn.btn-info.btn-xs{ href: edit_variant_admin_path( variant.id ) }
											Edit
										%a.btn.btn-danger.btn-xs{ href: variant_admin_path( variant.id ), data: { method: :delete, confirm: 'Are you sure?' } }
											Trash
							%tr
								%td{ colspan: 2 }
								%td
									= @experiment.trials.count
								%td{ colspan:  5}


					.well.white-well
						%a.pull-right{ href: '#new_experiment_url_pattern', data: { toggle: :modal, target: '#new_experiment_url_pattern' } }
							%i.fa.fa-plus
							Add
						%h4
							URL Patterns

						%table.table.table-light.table-bordered{ style: 'margin:0;' }
							%thead
								%th URL Pattern
								%th


							- if @experiment.experiment_url_patterns.empty?
								%tr
									%td{ colspan: 2 }
										\- No URL Patterns Found -

							- @experiment.experiment_url_patterns.each do |experiment_url_pattern|
								%tr
									%td
										= experiment_url_pattern.url_pattern
									%td
										%a.btn.btn-danger.btn-xs{ href: experiment_url_pattern_admin_path( experiment_url_pattern.id ), data: { method: :delete, confirm: 'Are you sure?' } }
											Trash


			.col-xs-4
				.well
					.form-group
						= f.label :conversion_event
						= f.select :conversion_event, Bunyan.event_categories.keys, {}, class: 'form-control'
						=# f.select :sample_type, [ '5050', 'weighted', 'random' ], {}, class: 'form-control'

					.form-group
						= f.label :conversion_path
						= f.text_field :conversion_path, class: 'form-control'

					.form-group
						= f.label :sample_type
						= f.select :sample_type, [ '5050', 'random' ], {}, class: 'form-control'
						=# f.select :sample_type, [ '5050', 'weighted', 'random' ], {}, class: 'form-control'


					.form-group
						= f.label :conclusion_type, "When the music's over show the:"
						= f.select :conclusion_type, [ 'control', 'winner', 'nothing' ], {}, class: 'form-control'
						=# f.select :sample_type, [ '5050', 'weighted', 'random' ], {}, class: 'form-control'

					.form-group
						= f.label :max_trials
						= f.text_field :max_trials, class: 'form-control'

					.form-group
						= f.label :start_at
						= f.text_field :start_at, value: current_user.to_local_tz( @experiment.start_at ), class: 'form-control datetimepicker'
					.form-group
						= f.label :end_at
						= f.text_field :end_at, value: current_user.to_local_tz( @experiment.end_at ), class: 'form-control datetimepicker'
					.form-group
						= f.label :conversion_window_days, "Conversion Window (days)"
						= f.number_field :conversion_window_days, class: 'form-control', min: 0, step: 1
					.form-group
						= f.label :status
						= f.collection_select :status, Edison::Experiment.statuses, :first, :first, {}, class: 'form-control'

					.form-group
						= f.submit 'Update', class: 'btn btn-primary'


= render 'edison/variant_admin/new_modal', args: { experiment_id: @experiment.id }
= render 'edison/experiment_url_pattern_admin/new_modal', args: { experiment_id: @experiment.id }

app/views/edison/experiment_admin/index.html.haml
.container-fluid
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					%a{ href: '/admin' }
						Admin
				%li
					Expeiments
		.col-xs-2
			%a.btn.btn-success{ data: { toggle: :modal, target: '#new_experiment' } }
				%i.fa.fa-plus-square
				New
	.row{ style: 'margin-top: 0' }
		.col-xs-6
			= raw paginate @experiments
		.col-xs-6
		

	.row
		.col-xs-12
			- if @experiments.blank?
				.well
					%h3
						No Experiments Found
			- else

				%table.table.table-light.table-bordered
					%thead
						%th
							Title
						%th
							Variants
						%th
							Trials
						%th
							Status
						%th
							Start
						%th
							End

					%tbody
						- @experiments.each do |experiment|
							%tr
								%td
									%a{ href: edit_experiment_admin_path( experiment ) }
										= experiment.title
								%td
									= experiment.variants.count
								%td
									= experiment.trials.count
								%td
									= experiment.status
								%td
									= experiment.start_at
								%td
									= experiment.end_at

								
								
								
= render 'new_modal'